from pbx_gs_python_utils.utils.Dev import Dev

from gw_bot.api.API_OSS_Bot import API_OSS_Bot



class Slack_Handler:

    def run(self,data):
        from gw_bot.helpers.Lambda_Helpers import log_to_elk
        result = None
        if "challenge" in data:              # required for Slack event check
            return data.get("challenge")
        #channel = data.get('channel')
        if data.get('event'):
            slack_event = data.get('event')
            if ("bot_id" in slack_event) is False:                      # this happens when the data was generated by an bot
                result = API_OSS_Bot().process_event(slack_event)          # add a `return` here to see message in test
        elif data.get('body'):                                          # this needs this change in API_Gateway to work https://github.com/nateyolles/slack-pokerbot/issues/1
            #log_to_elk('with body', f'{data.get("body")}')
            return API_OSS_Bot().process_posted_body(data)

        #if channel is None:                                             # to help with unit tests
        #    return result
        return "200 OK"
